[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]

[workspace.dependencies]
hdi = "=0.2.4"
hdk = "=0.1.4"
serde = "1.0"
image = "0.24.7"

[workspace.dependencies.profiles]
path = "dnas/requests_and_offers/zomes/coordinator/profiles"

[workspace.dependencies.profiles_integrity]
path = "dnas/requests_and_offers/zomes/integrity/profiles"
